// <auto-generated />
using System;
using BackendAwSmartstay.API.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendAwSmartstay.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BackendAwSmartstay.API.Accommodations.Domain.Model.Aggregates.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("amenities");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<int>("HostId")
                        .HasColumnType("int")
                        .HasColumnName("host_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_hotels");

                    b.ToTable("hotels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Jr. de la Unión 958",
                            Amenities = "[\"Wifi\",\"Restaurante\",\"Bar\"]",
                            City = "Lima",
                            Country = "Peru",
                            Description = "Historic hotel in the center of Lima.",
                            HostId = 1,
                            ImageUrl = "https://placehold.co/600x400/3498DB/FFFFFF?text=Bolivar",
                            Name = "Grand Hotel Bolivar",
                            Type = "Hotel"
                        },
                        new
                        {
                            Id = 2,
                            Address = "San Blas 123",
                            Amenities = "[\"Desayuno\",\"Wifi\",\"Gimnasio\"]",
                            City = "Cusco",
                            Country = "Peru",
                            Description = "Experience the mystic energy of the Andes.",
                            HostId = 1,
                            ImageUrl = "https://placehold.co/600x400/E67E22/FFFFFF?text=Andean",
                            Name = "Cusco Andean Lodge",
                            Type = "Lodge"
                        });
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Accommodations.Domain.Model.Aggregates.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("amenities");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_rooms");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("i_x_rooms_hotel_id");

                    b.HasIndex("RoomTypeId")
                        .HasDatabaseName("i_x_rooms_room_type_id");

                    b.ToTable("rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Amenities = "[\"Wifi\",\"TV\"]",
                            Description = "Room 101 - Standard view.",
                            HotelId = 1,
                            Price = 85.00m,
                            RoomTypeId = 1,
                            Status = "Clean"
                        },
                        new
                        {
                            Id = 102,
                            Amenities = "[\"Wifi\",\"TV\",\"Minibar\"]",
                            Description = "Room 102 - Plaza view with balcony.",
                            HotelId = 1,
                            Price = 150.00m,
                            RoomTypeId = 2,
                            Status = "Clean"
                        },
                        new
                        {
                            Id = 201,
                            Amenities = "[\"Jacuzzi\",\"Wifi\",\"Desayuno\",\"Chimenea\"]",
                            Description = "Suite 201 - Panoramic mountain view.",
                            HotelId = 2,
                            Price = 320.00m,
                            RoomTypeId = 3,
                            Status = "Dirty"
                        });
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Accommodations.Domain.Model.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_amenities_catalogs");

                    b.ToTable("amenities_catalogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "General",
                            Name = "Wifi"
                        },
                        new
                        {
                            Id = 2,
                            Category = "General",
                            Name = "Piscina"
                        },
                        new
                        {
                            Id = 3,
                            Category = "General",
                            Name = "Gimnasio"
                        },
                        new
                        {
                            Id = 4,
                            Category = "General",
                            Name = "Restaurante"
                        },
                        new
                        {
                            Id = 5,
                            Category = "General",
                            Name = "Parking"
                        },
                        new
                        {
                            Id = 6,
                            Category = "General",
                            Name = "Spa"
                        },
                        new
                        {
                            Id = 7,
                            Category = "General",
                            Name = "Bar"
                        },
                        new
                        {
                            Id = 8,
                            Category = "General",
                            Name = "Desayuno"
                        });
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Accommodations.Domain.Model.Entities.HotelCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_hotel_categories");

                    b.ToTable("hotel_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hotel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Posada"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lodge"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hostal"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cabaña"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Resort"
                        });
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Accommodations.Domain.Model.Entities.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_room_types");

                    b.ToTable("room_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cozy room for solo travelers.",
                            Name = "Single Standard"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Spacious room for couples or business.",
                            Name = "Double Deluxe"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Luxury suite with best views.",
                            Name = "Presidential Suite"
                        });
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Bookings.Domain.Model.Aggregates.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("check_in_date");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("check_out_date");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("guest_email");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("guest_name");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_bookings");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("BackendAwSmartstay.API.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChainId")
                        .HasColumnType("int")
                        .HasColumnName("chain_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<int>("TokenVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("token_version");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex(new[] { "Status" }, "i_x_users_status")
                        .HasDatabaseName("i_x_users_status");

                    b.HasIndex(new[] { "Username" }, "i_x_users_username")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Payments.Domain.Model.Aggregates.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("card_holder_name");

                    b.Property<string>("CardNumberMasked")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("card_number_masked");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payment_method");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("p_k_payments");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_profiles");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Accommodations.Domain.Model.Aggregates.Room", b =>
                {
                    b.HasOne("BackendAwSmartstay.API.Accommodations.Domain.Model.Aggregates.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_rooms_hotels_hotel_id");

                    b.HasOne("BackendAwSmartstay.API.Accommodations.Domain.Model.Entities.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_rooms_room_types_room_type_id");

                    b.Navigation("Hotel");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.OwnsOne("BackendAwSmartstay.API.Profiles.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("email_address");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.OwnsOne("BackendAwSmartstay.API.Profiles.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.OwnsOne("BackendAwSmartstay.API.Profiles.Domain.Model.ValueObjects.StreetAddress", "Address", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_country");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_street");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Accommodations.Domain.Model.Aggregates.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
